version: '2'
services:
  #######################################
  # Elasticsearch
  #######################################
  elasticsearch:
    build:
      context: ../docker/elasticsearch/
    ports:
      - 19200:9200
      - 19300:9300
    env_file:
      - ../.env
      - ../etc/environment.yml
      - ../etc/environment.development.yml
    environment:
      - VIRTUAL_HOST=elasticsearch.${PROJECT_NAME}.lvh.me
      - VIRTUAL_PORT=9200
