version: '2'
services:
  #######################################
  # MySQL server
  #######################################
  mysql:
    build:
      context: ../docker/mysql/
      #dockerfile: MySQL-5.5.Dockerfile
      #dockerfile: MySQL-5.6.Dockerfile
      #dockerfile: MySQL-5.7.Dockerfile
      #dockerfile: MariaDB-5.5.Dockerfile
      dockerfile: MariaDB-10.Dockerfile
      #dockerfile: Percona-5.5.Dockerfile
      #dockerfile: Percona-5.6.Dockerfile
      #dockerfile: Percona-5.7.Dockerfile
    network_mode: bridge
    env_file:
      - ../etc/environment.yml
      - ../etc/environment.development.yml