version: '2'
services:
  postgres:
    build:
      context: ../docker/postgres/
      dockerfile: Postgres-9.4.Dockerfile
      #dockerfile: Postgres-9.5.Dockerfile
    ports:
      - 15432:5432
    env_file:
      - ../etc/environment.yml
      - ../etc/environment.development.yml
